# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-12 21:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Priprava',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolicina', models.FloatField()),
                ('mera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getrecipe.Mera')),
            ],
        ),
        migrations.CreateModel(
            name='Recept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=200)),
                ('ocena', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('povezava', models.URLField()),
                ('povezava_do_slike_jedi', models.URLField(max_length=500, null=True)),
                ('zahtevnost', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('cas_priprave', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('postopek', models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Sestavina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TipJedi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='recept',
            name='sestavine',
            field=models.ManyToManyField(through='getrecipe.Priprava', to='getrecipe.Sestavina'),
        ),
        migrations.AddField(
            model_name='recept',
            name='tipi',
            field=models.ManyToManyField(to='getrecipe.TipJedi'),
        ),
        migrations.AddField(
            model_name='priprava',
            name='recept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getrecipe.Recept'),
        ),
        migrations.AddField(
            model_name='priprava',
            name='sestavina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getrecipe.Sestavina'),
        ),
    ]
