# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getrecipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='priprava',
            name='kolicina',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
