# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-12 21:42
from __future__ import unicode_literals

from django.db import migrations
import csv

class Migration(migrations.Migration):

    def populate_db(apps, schema_editor):
        Sestavina = apps.get_model('getrecipe', 'Sestavina')
        Mera = apps.get_model('getrecipe', 'Mera')
        Priprava = apps.get_model('getrecipe', 'Priprava')
        Recept = apps.get_model('getrecipe', 'Recept')

        with open('razne_mere.csv') as f:
            reader = csv.reader(f)
            for row in reader:
                if len(row) > 0:
                    m, c = Mera.objects.get_or_create(ime = row[0])
                    #nova_mera = Mera(ime = row[0])
                    #nova_mera.save()
                
        with open('razne_sestavine.csv') as f:
            reader = csv.reader(f)
            for row in reader:
                if len(row) > 0:
                    s,c = Sestavina.objects.get_or_create(ime=row[0])
                    #nova_sestavina = Sestavina(ime = row[0])
                    #nova_sestavina.save()
            
        with open('glavni_recepti.csv') as f:
            reader = csv.reader(f)
            for row in reader:
                if len(row) > 5:
                    ime, tezavnost, cas, url_slike, url_recepta, postopek = row
                    r, c = Recept.objects.get_or_create(ime = ime, zahtevnost = int(tezavnost),
                                                           cas_priprave = int(cas), povezava_do_slike_jedi = url_slike,
                                                           povezava = url_recepta, postopek = postopek, ocena = 0)
##            nov_recept = Recept()
##            nov_recept.ime = ime
##            nov_recept.zahtevnost = int(tezavnost)
##            nov_recept.cas_priprave = int(cas)
##            nov_recept.povezava_do_slike_jedi = url_slike
##            nov_recept.povezava = url_recepta
##            nov_recept.postopek = postopek
##            nov_recept.save()

    dependencies = [
        ('getrecipe', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_db)
    ]
